# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-09 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=10)),
                ('source', models.FileField(upload_to='projects/%Y/%m/%d/')),
                ('decompressed', models.CharField(max_length=255)),
            ],
        ),
    ]
